# Generated by Django 5.2.4 on 2025-08-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blog_category_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog_category',
            new_name='Prod_category',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gift_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='introducer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='position',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
