# Generated by Django 5.2.4 on 2025-10-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('payment confirmation pending from admin', 'Payment Confirmation Pending from Admin')], default='pending', max_length=50),
        ),
    ]
